apiVersion: apps/v1
kind: Deployment
metadata:
  name: borderflow-api-sa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borderflow-api-sa
  template:
    metadata:
      labels:
        app: borderflow-api-sa
    spec:
      containers:
      - name: api
        image: borderflow-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: SITE
          value: "sa"